test ci

diff --git a/.github/workflows/tests-ci.yml b/.github/workflows/tests-ci.yml
--- a/.github/workflows/tests-ci.yml
+++ b/.github/workflows/tests-ci.yml
@@ -36,76 +36,61 @@ jobs:
     - name: Restore
       run: dotnet restore "${{ env.Solution_Name }}"
 
-    - name: Build and analyze
+    - name: Build
+      run: dotnet build "${{ env.Solution_Name }}" --configuration Release --no-restore
+
+    - name: Run SonarCloud analysis and upload coverage
       env:
-        GITHUB_TOKEN: ${{ secrets.GH_APIKEY }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-      shell: bash
-      run: |
-          # dotnet-sonarscanner begin \
-          # /k:"thorstenalpers_Finance.NET" \
-          # /o:"thorstenalpers" \
-          # /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
-          # /d:sonar.host.url="https://sonarcloud.io" \
-          # /d:sonar.scanner.scanAll=false \
-          # /d:sonar.sources="src" \
-          # /d:sonar.tests="tests" \
-          # /d:sonar.test.inclusions="tests/**/*.cs" \
-          # /d:sonar.exclusions="**/*.html"
-
-          dotnet build "${{ env.Solution_Name }}" --configuration Release --no-restore
-          # dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
-
-    - name: Run tests
-      shell: pwsh
-      run: |
-          dotnet test "${{ env.Test_Project_Path }}" --collect:"XPlat Code Coverage" --results-directory ./TestResults/Tests --configuration Release --logger "console;verbosity=detailed"
-          if ($LASTEXITCODE -ne 0) {
-            Write-Host "Tests failed"
-            exit 1
-          }
-          reportgenerator -reports:./TestResults/Tests/**/coverage.cobertura.xml -targetdir:./TestResults/Reports -reporttypes:"Html;lcov;SonarQube;Cobertura"
-      env:
-          FinanceNet__AlphaVantageApiKey: ${{ secrets.ALPHAVANTAGEAPIKEY }}
-
-    # - name: Run SonarCloud analysis and upload coverage
-    #   env:
-    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-    #   run: |
-    #     dotnet-sonarscanner begin \
-    #         /k:"thorstenalpers_Finance.NET" \
-    #         /o:"thorstenalpers" \
-    #         /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
-    #         /d:sonar.host.url="https://sonarcloud.io" \
-    #         /d:sonar.scanner.scanAll=false \
-    #         /d:sonar.exclusions="**/*.html"
-
-    #     dotnet build "${{ env.Solution_Name }}" --configuration Release --no-restore        
-    
-    #     dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
-
-    - name: Run SonarCloud analysis
-      env:
-        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Ensure SONAR_TOKEN is set in your repository secrets
       run: |
         dotnet-sonarscanner begin \
-          /k:"thorstenalpers_Finance.NET" \
-          /o:"thorstenalpers" \
-          /d:sonar.coverage.lcov.reportPaths="**/TestResults/Reports/SonarQube.xml" \
-          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
-          /d:sonar.host.url="https://sonarcloud.io" \
-          /d:sonar.scanner.scanAll=false \
-          /d:sonar.test.inclusions="tests/**/*.cs" \
-          /d:sonar.exclusions="**/*.html"        
+            /k:"thorstenalpers_Finance.NET" \
+            /o:"thorstenalpers" \
+            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
+            /d:sonar.host.url="https://sonarcloud.io" \
+            /d:sonar.scanner.scanAll=false \
+            /d:sonar.exclusions="**/*.html"
+
         dotnet build "${{ env.Solution_Name }}" --configuration Release --no-restore        
+        dotnet test "${{ env.Test_Project_Path }}" --collect:"XPlat Code Coverage" --results-directory ./TestResults/Tests --configuration Release --logger "console;verbosity=detailed" 
+
         dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
+
+
+    # - name: Run tests
+    #   shell: pwsh
+    #   run: |
+    #       dotnet test "${{ env.Test_Project_Path }}" --collect:"XPlat Code Coverage" --results-directory ./TestResults/Tests --configuration Release --logger "console;verbosity=detailed" 
+    #       if ($LASTEXITCODE -ne 0) {
+    #         Write-Host "Tests failed"
+    #         exit 1
+    #       }
+    #       reportgenerator -reports:./TestResults/Tests/**/coverage.cobertura.xml -targetdir:./TestResults/Reports -reporttypes:"Html;lcov;SonarQube;Cobertura"
+    #   env:
+    #       FinanceNet__AlphaVantageApiKey: ${{ secrets.ALPHAVANTAGEAPIKEY }}
+
+    # - name: Run SonarCloud analysis
+    #   env:
+    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  Ensure SONAR_TOKEN is set in your repository secrets
+    #   run: |
+    #     dotnet-sonarscanner begin \
+    #       /k:"thorstenalpers_Finance.NET" \
+    #       /o:"thorstenalpers" \
+    #       /d:sonar.coverage.lcov.reportPaths="**/TestResults/Reports/SonarQube.xml" \
+    #       /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
+    #       /d:sonar.host.url="https://sonarcloud.io" \
+    #       /d:sonar.scanner.scanAll=false \
+    #       /d:sonar.test.inclusions="tests/**/*.cs" \
+    #       /d:sonar.exclusions="**/*.html"        
+    #     dotnet build "${{ env.Solution_Name }}" --configuration Release --no-restore        
+    #     dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
 
     # - name: Upload code coverage to SonarCloud
     #   shell: bash
     #   run: |
     #     curl -u ${{ secrets.SONAR_TOKEN }} \
     #       -X POST \
-    #       -F "file=@./TestResults/Reports/SonarQube.xml" \
+    #       -F "file=./TestResults/Reports/SonarQube.xml" \
     #       "https://sonarcloud.io/api/qualitygates/project_status?projectKey=thorstenalpers_Finance.NET"
     #     curl -u ${{ secrets.SONAR_TOKEN }} \
     #       "https://sonarcloud.io/api/qualitygates/project_status?projectKey=thorstenalpers_Finance.NET"
@@ -113,7 +98,7 @@ jobs:
     - name: Upload to Coveralls
       uses: coverallsapp/github-action@v2
       with:
-        path-to-lcov: ./TestResults/Reports/lcov.info
+        path-to-lcov: ./TestResults/Reports/SonarQube.xml
       env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
            
